### ISSUE TITLE
Realidad aumentada del Objeto 3D con Animacion

### ISSUE THREAD

**Issue by Abraham890** [SistemasTecTlaxiaco/actividad-6-realidad-aumentada-de-objeto-3d-con-animacion-dream-team1-0#1]
[Animacion.pdf](https://github.com/SistemasTecTlaxiaco/actividad-6-realidad-aumentada-de-objeto-3d-con-animacion-dream-team1-0/files/11124711/Animacion.pdf)

**Comment by carlos-chrs** [comment]
Muy Bien Hecho.
17/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado
